### PR TITLE
Doc and test updates

### PR DESCRIPTION
**Pull request by ehoogerbeets**
- added API documentation
- now can test on web browsers automatically

### CODE REVIEW

**Comment by gouniLee** [comment]
looks like `npm run doc` and `npm run doc:html` are not working.
When I run `npm run doc`, looks like the procss is stop. and `npm run doc:html`, it shows an error.

**Comment by ehoogerbeets** [comment]
Yes, ilib-locale needs to go first...

**Comment by ehoogerbeets** [comment]
Oh wait... I was thinking of ilib-common... this one should work. I'll check it out.

**Comment by ehoogerbeets** [comment]
Hm... it works for me... Goun, did you do `npm install` before running any of these commands? There are many new dependencies in this PR.

**Comment by gouniLee** [comment]
I tried again. and npm run doc:html works fine. 

I want to make sure, when I run, `npm run doc`, 
with below status,  won't terminate, 
actually, it's the same as another plugin too. is it the correct result or something wrong with my desktop?
```
goun@goun-LGE:~/Source/opensource_iLib/ilib-locale$ npm run doc
> ilib-locale@1.0.1 doc /home/goun/Source/opensource_iLib/ilib-locale
> jsdoc2md -c jsdoc.json --separators --source src/* -m table > docs/Locale.md

```

**Comment by ehoogerbeets** [comment]
It completes properly on my Ubuntu machine and my work Mac. It is written in javascript, so you should be able to run it by hand in the debugger to see what it is doing:

`node --inspect-brk node_modules/.bin/jsdoc2md -c jsdoc.json --separators --source src/* -m table > docs/Locale.md`

**Review by gouniLee — APPROVED** [review]

**Pull request merged**
