### PR TITLE
Convert to jest

### PR DESCRIPTION
**Pull request by ehoogerbeets**
- convert all tests to jest
- update dependencies
- can now test on headless browsers using karma
- still works on node 10 to 20
- made platform detection a little more efficient by using cached platform name if it is available instead of detecting the platform afresh each time
- made platform detection unit tests work better by simulating the environment better

### CODE REVIEW

**Comment by gouniLee** [comment]
I ran `npm run test:web` command to see the result through the browser, 
but only saw the result below. how can execute the browser result?
```
goun@goun-LGE:~/Source/opensource_iLib/ilib-env$ npm run test:web

> ilib-env@1.3.3 test:web
> LANG=en_US.UTF8 node --experimental-vm-modules node_modules/.bin/karma start --reporters dots --single-run

webpack was not included as a framework in karma configuration, setting this automatically...
Webpack bundling...
asset commons.js 48.7 KiB [emitted] (name: commons) (id hint: commons)
asset runtime.js 6.41 KiB [emitted] (name: runtime)
asset karma-setup.562878397.js 1010 bytes [emitted] (name: karma-setup.562878397)
asset env.test.268365165.js 1010 bytes [emitted] (name: env.test.268365165)
Entrypoint karma-setup.562878397 56.1 KiB = runtime.js 6.41 KiB commons.js 48.7 KiB karma-setup.562878397.js 1010 bytes
Entrypoint env.test.268365165 56.1 KiB = runtime.js 6.41 KiB commons.js 48.7 KiB env.test.268365165.js 1010 bytes
webpack 5.89.0 compiled successfully in 975 ms
04 12 2023 10:30:47.348:INFO [karma-server]: Karma v6.4.2 server started at http://localhost:9876/
04 12 2023 10:30:47.349:INFO [launcher]: Launching browsers ChromeHeadless with concurrency unlimited
04 12 2023 10:30:47.359:INFO [launcher]: Starting browser ChromeHeadless
04 12 2023 10:30:47.935:INFO [Chrome Headless 118.0.5993.88 (Linux x86_64)]: Connected on socket Wd1vkk_wSOfDw0OLAAAB with id 69054710
.......................................................
Chrome Headless 118.0.5993.88 (Linux x86_64): Executed 55 of 55 SUCCESS (0.042 secs / 0.022 secs)
```

**Comment by ehoogerbeets** [comment]
That is running in the browser! Of course, it is headless, meaning that no window appears on your screen, which makes it CI-friendly. If you want to see the window and debug on your browser, you should find the line in the karma.conf.js file where it says "ChromeHeadless" and change it to just "Chrome".  Later, we can also add "Firefox" and some other browsers, but I'm having a problem running Firefox on my system right now. Until that's resolved, I'm just doing Chrome.

**Comment by gouniLee** [comment]
> Chrome Headless 118.0.5993.88 (Linux x86_64): Executed 55 of 55 SUCCESS (0.042 secs / 0.022 secs)

oh, I see. It's the correct result. that's cool :)
I also modified `ChromHeadless` to `Chrome`. then the browser poped and and disappeared very quickly. What can  I do if i want to debug through browser? I tried run node-inspecor and put `debugger` in test files, but seem not work.

**Comment by ehoogerbeets** [comment]
In the package.json, remove the "--single-run" option to karma and it will stay around. Every time you save a source file, it will rerun webpack and rerun the tests, and you should be able to see it in the debugger.

Maybe we should make a "debug:web" script in the package.json for this?

**Comment by gouniLee** [comment]
> In the package.json, remove the "--single-run" option to karma and it will stay around. Every time you save a source file, it will rerun webpack and rerun the tests, and you should be able to see it in the debugger.
> 
> Maybe we should make a "debug:web" script in the package.json for this?

can I put the breakpoint in env.test.js test file?

**Comment by ehoogerbeets** [comment]
Yes, but you have to put at least one `debugger;` statement in first in order to get it to stop so you can then put the breakpoint.

**Comment by gouniLee** [comment]
yes, It works. I expected to stop right away at my breakpoint. but I had to do one more browser refreshment when the browser opened

**Review by gouniLee — APPROVED** [review]

**Pull request merged**
