### PR TITLE
True singletons

### PR DESCRIPTION
**Pull request by ehoogerbeets**
* Previously when two different copies of ilib-env are loaded from different node_modules
  directories or an app loads two copies of ilib-env with different version
  numbers, they will be copies of each other with separate variables in
  them. When that happens, setting
  the platform, timezone, or locale for the entire app will not work because
  each copy of ilib-env will have a different idea of what those variables are.
  The solution is to save the settings in the global scope so that they are
  shared between all copies of ilib-env.
* update dependencies

### CODE REVIEW

**Comment by gouniLee** [comment]
I can't imagine the situation well.  One specific version of ilib-env can be used for node and browser both. is this cause the problem case? Is there a possible case to load and use two versions in one app?

**Comment by ehoogerbeets** [comment]
In nodejs, if you depend on version 1.2.1 of a package X, and something else you depend on also depends on package X but at version 1.1.0, then you will have two copies of package X on your node_modules:

node_modules/X  <- v1.21
node_modules/otherpackage/node_modules/X <- v1.1.0

Similarly, if you have a project with its own node_modules with package X, and you have the global node_modules with package X, even if they have the same version number, node will load 2 different copies of X. Each copy will have its own values for its package variables and static data. This is because nodejs resolves a path in a require/import call to an absolute path and then compares it to what it has loaded already in memory. Since the local and global copies of X package have different paths, nodejs assumes they are different packages which happen to have the same name, and loads it into memory twice.

Other JS engines do similar things with packages.

The solution is to put all of the truly global data, like for example the locale or the timezone, into the global scope instead of the package's scope. That way, all copies of the package access the same copies of the data. Having global data is not recommended usually, but this type of data are settings from the external environment and are truly global and should not change for the most part. They are not some temporary data that we are storing in the global scope for convenience.

**Comment by ehoogerbeets** [comment]
@gouniLee please re-review after the above explanation

**Comment by gouniLee** [comment]
oh. sorry for the late review. As you said if it's different from the behavior of other packages do. not sure if would cause another side effect even if your could sure it would b ok.  we will see and approve your continue work.

**Review by gouniLee — APPROVED** [review]

**Pull request merged**
